blank_issues_enabled: false
contact_links:
  - name: Support via Discord
    url: https://discord.gg/AD3UP37
    about: Get chat style help from knowledgeable users and developers.
  - name: Support via Reddit
    url: https://reddit.com/r/radarr
    about: Get forum style help from knowledgeable users and developers.
